Algoritmo "OPERAÇÕES BÁSICAS"

Var
 N1: inteiro
 N2: inteiro


Inicio
      escreval("Digite o primeiro número")
      leia(N1)
      
      escreval("Digite o segundo número")
      leia(N2)
      
      escreval ("a soma dos valores é igual a:",N1+N2)
      
      escreval ("a subtração dos valores é igual a:",N1-N2)
      
      escreval ("a multiplicação dos valores é igual a",N1*N2)
      
      escreval ("a divisão dos valores é igual a",N1/N2)

Fimalgoritmo