Algoritmo "TROCA DE VARIÁVEIS"

Var
   A: inteiro
   B: inteiro
   C: inteiro

Inicio
      escreva("Digite o valor da variável A:")
      leia(A)
      
      escreva("Digite o valor da variável B:")
      leia(B)
      
      C <- A
      A <- B
      B <- C
      
      escreval("o valor da variável A é:", A)
      
      escreval("O valor da variável B é:", B)

Fimalgoritmo