Algoritmo "RENDIMENTO DA POUPANÇA"

Var
   Valor1: real
   Valor2: real
   Valor3: real


Inicio
              escreva("Digite o valor que será depositado na poupança:R$")
              leia(Valor1)
              
              Valor2 <- Valor1 * 0.7
              Valor3 <- Valor2 / 100
              escreva("O valor de rendimento no aniversário mensal da conta será de:R$",Valor1 + Valor3)


Fimalgoritmo